#!/usr/bin/env python3
"""Tests for the `cper` Python extension (CPER and CPAD decode/encode).

Run via `meson test` when the project is configured with -Dpython=enabled,
or directly with the built extension on PYTHONPATH/LD_LIBRARY_PATH.

Binary fixtures are loaded from the maintained example files rather than
hardcoded, so they stay valid as the CPER/CPAD formats evolve.
"""

import os

import cper


def _examples_dir():
    env = os.environ.get("LIBCPER_EXAMPLES")
    if env:
        return env
    # Fall back to the repository examples directory relative to this file.
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                        "examples")


def _load_hex(name):
    path = os.path.join(_examples_dir(), name)
    with open(path, "r") as f:
        return bytes.fromhex("".join(f.read().split()))


# CPER and CPAD fixtures generated by the project's own generator; these
# example files are regenerated whenever the formats change.
CPER_BYTES = _load_hex("generic.cperhex")
CPAD_BYTES = _load_hex("cpad-os-generic.cpadhex")


def test_parse_cper():
    ir = cper.parse(CPER_BYTES)
    assert isinstance(ir, dict)
    assert "header" in ir
    assert "sectionDescriptors" in ir
    assert "sections" in ir


def test_parse_cpad():
    ir = cper.parse_cpad(CPAD_BYTES)
    assert isinstance(ir, dict)
    assert "header" in ir
    assert "sectionDescriptors" in ir
    assert "sections" in ir
    # CPAD-specific fields.
    assert "urgency" in ir["header"]
    assert "actionID" in ir["sectionDescriptors"][0]


def test_cper_roundtrip():
    ir = cper.parse(CPER_BYTES)
    encoded = cper.to_cper(ir)
    assert isinstance(encoded, bytes)
    # Re-decoding the re-encoded record yields an identical IR, and the
    # encoding is a stable fixpoint.
    assert cper.parse(encoded) == ir
    assert cper.to_cper(cper.parse(encoded)) == encoded


def test_cpad_roundtrip():
    ir = cper.parse_cpad(CPAD_BYTES)
    encoded = cper.to_cpad(ir)
    assert isinstance(encoded, bytes)
    # Generated records round-trip byte-for-byte.
    assert encoded == CPAD_BYTES
    assert cper.parse_cpad(encoded) == ir


def test_uint64_fidelity():
    # A 64-bit value above INT64_MAX must round-trip without truncation.
    # Use whichever fixture exposes an integer-valued section field.
    ir = cper.parse_cpad(CPAD_BYTES)
    section = ir["sections"][0]
    body = next(iter(section.values()))
    int_keys = [k for k, v in body.items() if isinstance(v, int)]
    assert int_keys, "expected at least one integer field to test"
    key = int_keys[0]
    big = 0xFFFFFFFFFFFFFFF0
    body[key] = big
    decoded = cper.parse_cpad(cper.to_cpad(ir))
    assert next(iter(decoded["sections"][0].values()))[key] == big


def test_invalid_input_raises():
    raised = False
    try:
        cper.parse(b"not a real cper record")
    except ValueError:
        raised = True
    assert raised, "parse() should raise ValueError on invalid input"


def main():
    tests = [
        test_parse_cper,
        test_parse_cpad,
        test_cper_roundtrip,
        test_cpad_roundtrip,
        test_uint64_fidelity,
        test_invalid_input_raises,
    ]
    for t in tests:
        t()
        print(f"PASS {t.__name__}")
    print("\nAll pycper tests passed.")


if __name__ == "__main__":
    main()
